### ISSUE TITLE
The link to Google+ doesn't work since...

### ISSUE THREAD

**Issue by rynkowsg** [mariuszgil/awesome-eventstorming#14]
... since Google+ had been shut down in April.

The link [EventStormers Google+ Community](https://plus.google.com/u/0/communities/113258571348605620818) at the [Online Communities](https://github.com/mariuszgil/awesome-eventstorming#online-communities) section.

**Comment by ylorph** [comment]
@rynkowsg the link has been corrected with #18

**Comment by rynkowsg** [comment]
Thanks
